--LIST OF MANAGER INCLUDES ID, LAST_NAME AND DEPARTMENT NAME
SELECT EM.EMPLOYEE_ID,EM.FIRST_NAME,EM.LAST_NAME,DP.DEPARTMENT_NAME FROM EMPLOYEES AS EM 
JOIN DEPARTMENTS AS DP ON EM.EMPLOYEE_ID=DP.MANAGER_ID

--LIST OF LOCATION OF ALL DEPARTMENT INCLUDES DEPARTMENT_ID, CITY, COUNTRY_NAME AND REGION_NAME
SELECT DP.DEPARTMENT_ID,DP.DEPARTMENT_NAME,LC.CITY,CT.COUNTRY_NAME,RG.REGION_NAME FROM DEPARTMENTS AS DP JOIN LOCATIONS AS LC ON 
DP.LOCATION_ID=LC.LOCATION_ID JOIN COUNTRIES AS CT ON LC.COUNTRY_ID=CT.COUNTRY_ID JOIN 
REGIONS AS RG ON RG.REGION_ID=CT.REGION_ID


--LIST EMPLOYESS INCLUDES EMPLOYEES LAST_NAME, JOB_TITLE AND DEPARTMENT NAME
SELECT EM.LAST_NAME, DP.DEPARTMENT_NAME, J.JOB_TITLE FROM EMPLOYEES AS EM JOIN DEPARTMENTS AS DP ON
EM.DEPARTMENT_ID=DP.DEPARTMENT_ID JOIN JOBS AS J ON EM.JOB_ID=J.JOB_ID


--LIST OF EMPLOYEES OF STEVEN KING INCLUDES EMPLOYEES LAST_NAME, DEPARTMENT_NAME AND JOB_TITLE
SELECT EM.LAST_NAME, DP.DEPARTMENT_NAME,J.JOB_TITLE FROM EMPLOYEES AS EM JOIN DEPARTMENTS AS DP 
ON EM.DEPARTMENT_ID=DP.DEPARTMENT_ID JOIN JOBS AS J ON EM.JOB_ID=J.JOB_ID WHERE EM.MANAGER_ID =
(SELECT EM.EMPLOYEE_ID FROM EMPLOYEES AS EM WHERE EM.FIRST_NAME='Steven' AND EM.LAST_NAME='King')


--FIND EMPLOYEES WHO HAVE LETTER 'A' IN NAMES
SELECT EM.LAST_NAME, DP.DEPARTMENT_NAME FROM EMPLOYEES AS EM JOIN DEPARTMENTS AS DP ON
EM.DEPARTMENT_ID=DP.DEPARTMENT_ID WHERE EM.LAST_NAME LIKE 'A%'


--LIST OF EMPLOYEES WORKING IN TORONTO INCLUDES EMPLOYEES LAST_NAME, DEPARTMENT_NAME
SELECT EM.LAST_NAME, DP.DEPARTMENT_NAME FROM EMPLOYEES AS EM JOIN DEPARTMENTS AS DP ON
EM.DEPARTMENT_ID=DP.DEPARTMENT_ID JOIN LOCATIONS AS LC ON
DP.LOCATION_ID=LC.LOCATION_ID WHERE LC.CITY='TORONTO'


--LIST OF EMPLOYEES WHO WAS HIRED IN 2000 INCLUDES EMPLOYEES ID, EMPLOYEES LAST_NAME AND JOB TITLES
SELECT EM.EMPLOYEE_ID, EM.LAST_NAME, J.JOB_TITLE FROM EMPLOYEES AS EM JOIN JOBS AS J
ON EM.JOB_ID=J.JOB_ID WHERE YEAR(EM.HIRE_DATE)=2000


--THE NUMBER OF EMPLOYEES WHICH WAS HIRED BY YEAR
SELECT YEAR(EM.HIRE_DATE) AS [YEAR],COUNT(EM.EMPLOYEE_ID) 
AS [NUMBER OF EMPLOYEES] FROM EMPLOYEES AS EM 
GROUP BY YEAR(EM.HIRE_DATE)


--THE NUMBER OF DEPARTMENTS IN EACH LOCATION
SELECT LC.LOCATION_ID, LC.CITY, COUNT(DP.DEPARTMENT_ID) FROM DEPARTMENTS AS DP JOIN LOCATIONS AS LC 
ON DP.LOCATION_ID=LC.LOCATION_ID GROUP BY LC.LOCATION_ID, LC.CITY


--THE NUMBER OF DEPARTMENTS IN EACH COUNTRY
SELECT CT.COUNTRY_ID, CT.COUNTRY_NAME, COUNT(DP.DEPARTMENT_ID) AS [NUMBER OF DEPARTMENTS]
FROM DEPARTMENTS AS DP JOIN LOCATIONS AS LC 
ON DP.LOCATION_ID=LC.LOCATION_ID JOIN COUNTRIES AS CT ON LC.COUNTRY_ID=CT.COUNTRY_ID
GROUP BY CT.COUNTRY_ID, CT.COUNTRY_NAME


--THE NUMBER OF EMPLOYEES IN EACH DEPARTMENT
SELECT DP.DEPARTMENT_ID, DP.DEPARTMENT_NAME, COUNT(EM.EMPLOYEE_ID) AS [NUMBER OF EMPLOYEES]  
FROM DEPARTMENTS AS DP JOIN EMPLOYEES AS EM
ON EM.DEPARTMENT_ID=DP.DEPARTMENT_ID GROUP BY 
DP.DEPARTMENT_ID, DP.DEPARTMENT_NAME 


--LIST OF COUNTRIES WHICH HAVE NO DEPARTMENTS
SELECT * FROM COUNTRIES 
EXCEPT (SELECT CT.COUNTRY_ID, CT.COUNTRY_NAME, CT.REGION_ID FROM DEPARTMENTS AS DP JOIN LOCATIONS AS LC ON
DP.LOCATION_ID=LC.LOCATION_ID JOIN COUNTRIES AS CT ON LC.COUNTRY_ID=CT.COUNTRY_ID)


--RANGE OF SALARY OF EACH JOB
SELECT *,J.MAX_SALARY-J.MIN_SALARY AS [RANGE OF SALARY] FROM JOBS AS J
ORDER BY [RANGE OF SALARY] DESC


--AVERAGE SALARY OF EACH JOB
SELECT J.JOB_ID, J.JOB_TITLE, AVG(EM.SALARY) AS [AVG SALARY BY JOBS] 
FROM EMPLOYEES AS EM JOIN JOBS AS J ON
EM.JOB_ID=J.JOB_ID GROUP BY J.JOB_ID, J.JOB_TITLE 
ORDER BY [AVG SALARY BY JOBS] DESC


--LIST OF EMPLOYEES WHO LEFT
SELECT EM.EMPLOYEE_ID, EM.LAST_NAME,JH.END_DATE, J.JOB_TITLE FROM EMPLOYEES AS EM JOIN JOB_HISTORY AS JH
ON EM.EMPLOYEE_ID=JH.EMPLOYEE_ID JOIN JOBS AS J
ON JH.JOB_ID=J.JOB_ID


--THE NUMBER OF DAYS WORKING OF THEM
SELECT *,DATEDIFF(DAY, JH.START_DATE,JH.END_DATE) AS [NUMBER OF DAYS] FROM JOB_HISTORY AS JH
ORDER BY [NUMBER OF DAYS]

EXEC sp_listemployee @man_id=201


--CREATE A PROCEDURE WHICH RETURNS EMPLOYEES LAST_NAME, 
--EMPLOYEES HIRE_DATE, JOB_TITLE, EMPLOYEES SALARY, DEPARTMENT_NAME AND CITY WHEN INPUT IS EMPLOYEES ID
ALTER PROCEDURE em_info @em_id NUMERIC
AS
SELECT EM.LAST_NAME, EM.HIRE_DATE, J.JOB_TITLE, EM.SALARY, DP.DEPARTMENT_NAME, LC.CITY
FROM EMPLOYEES AS EM 
JOIN DEPARTMENTS AS DP ON EM.DEPARTMENT_ID=DP.DEPARTMENT_ID
JOIN JOBS AS J ON EM.JOB_ID=J.JOB_ID 
JOIN LOCATIONS AS LC ON LC.LOCATION_ID=DP.LOCATION_ID WHERE EM.EMPLOYEE_ID=@em_id

EXEC em_info @em_id=201

